# -*- coding: utf-8 -*-
"""Conversão.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tVzGTuvxAq8pLewPfOE7pALAAYoFqDtf
"""

# Solicita ao usuário que digite os três valores e converte para inteiros
valor1 = int(input("Digite o valor 1: "))
valor2 = int(input("Digite o valor 2: "))
valor3 = int(input("Digite o valor 3: "))

# Calcula a soma dos valores
valor_total = valor1 + valor2 + valor3

# Imprime o resultado na tela
print("A soma dos valores é:", valor_total)

valor1 = float(input("Digite um número: "))
valor2 = float(input("Digite outro número: "))
# Convertendo para inteiro (descarta a parte decimal)
valor1_inteiro = int(valor1)
valor_total = valor1 + valor2

# Exibindo a mensagem
print(f"O valor {valor1} é um número de ponto float e será convertido para o inteiro {valor1_inteiro}.")
print ("A soma dos valor é:",valor_total)

# Ordem Arimetica
compra1 = float(input("Digite o valor total da primeira R$: "))
compra2 = float(input("Digite o valor total da segunda compra R$: "))

total_item_1 = int(input("Digite o total de itens da compra1: "))
total_item_2 = int(input("Digite o total de itens da compra2: "))


# Calculando o preço unitário
preco_unitario_1 = compra1 / total_item_1
preco_unitario_2 = compra1 / total_item_2

# Imprimindo o resultado
print("O preço unitário da primeira compra é:", preco_unitario_1)
print("O preço unitário da primeira compra é:", preco_unitario_2)

valor_total_compra = compra1 + compra2
print("A soma dos valores é:",valor_total_compra)

valor_total_compra_itens = total_item_1 + total_item_2
print("A soma dos itens é:",valor_total_compra_itens)